// Auto-generated by stellar-contracts-kit
// Example usage for todo
// Contract : CDVMUWZ5Z5523B6G6RHLPREN3J7PL33E4KWRXAAQFUTDGBPRWIQ4DQYJ
// Network  : testnet
// @ts-check

import { StellarContractsKit } from 'stellar-contracts-kit'
// Types file: ./contracts/todo.js. Update the path below if using snippets elsewhere.
import { CONTRACT_ID } from './todo.js'

const kit = new StellarContractsKit({ network: 'testnet' })

// Connect wallet (opens picker modal if no wallet specified)
const { address } = await kit.connect()
console.log('Connected:', address)

// Load the contract client
const contract = await kit.contract(CONTRACT_ID)

// add_task(task: string) -> number
const { txHash: add_taskTxHash, result: add_taskResult } = await contract.add_task.invoke(
  '',  // task: string
)
console.log('add_task txHash:', add_taskTxHash, 'result:', add_taskResult)

// get_tasks() -> Map<number, string>
const { result: get_tasksResult } = await contract.get_tasks.read()
console.log('get_tasks:', get_tasksResult)

// delete_task(id: number) -> void
const { txHash: delete_taskTxHash } = await contract.delete_task.invoke(
  0,  // id: number
)
console.log('delete_task txHash:', delete_taskTxHash)
